//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString {
            get {
                return ((string)(this["SocialShopConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;User ID=socialshop")]
        public string SocialShopConnectionString1 {
            get {
                return ((string)(this["SocialShopConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString2 {
            get {
                return ((string)(this["SocialShopConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString3 {
            get {
                return ((string)(this["SocialShopConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString4 {
            get {
                return ((string)(this["SocialShopConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString5 {
            get {
                return ((string)(this["SocialShopConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString6 {
            get {
                return ((string)(this["SocialShopConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=SocialShop")]
        public string SocialShopConnectionString8 {
            get {
                return ((string)(this["SocialShopConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.0.13;Initial Catalog=SocialShop;Persist Security Info=True;User" +
            " ID=socialshop;Password=ssAdmin\\)!)^\\")]
        public string SocialShopConnectionString9 {
            get {
                return ((string)(this["SocialShopConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=socialshop")]
        public string SocialShopConnectionString10 {
            get {
                return ((string)(this["SocialShopConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.115\\SQL2008;Initial Catalog=SocialShop;Persist Security Inf" +
            "o=True;User ID=socialshop")]
        public string SocialShopConnectionString7 {
            get {
                return ((string)(this["SocialShopConnectionString7"]));
            }
        }
    }
}
