//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 

namespace VTCO.Utils.GoServices
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ByOnShopOnlineSoap", Namespace = "http://tempuri.org/")]
    public partial class ByOnShopOnline : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ByProductOperationCompleted;

        /// <remarks/>
        public ByOnShopOnline()
        {
            //this.Url = "http://bet168.vn/Webservice/ByOnShopOnline.asmx";
            this.Url = VTCO.Config.Global.Settings.Bet168URL;
        }

        /// <remarks/>
        public event ByProductCompletedEventHandler ByProductCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ByProduct", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ByProduct(string AccountName, int Mark, string ProductInfo, string PrivateKey)
        {
            object[] results = this.Invoke("ByProduct", new object[] {
                    AccountName,
                    Mark,
                    ProductInfo,
                    PrivateKey});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginByProduct(string AccountName, int Mark, string ProductInfo, string PrivateKey, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ByProduct", new object[] {
                    AccountName,
                    Mark,
                    ProductInfo,
                    PrivateKey}, callback, asyncState);
        }

        /// <remarks/>
        public int EndByProduct(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void ByProductAsync(string AccountName, int Mark, string ProductInfo, string PrivateKey)
        {
            this.ByProductAsync(AccountName, Mark, ProductInfo, PrivateKey, null);
        }

        /// <remarks/>
        public void ByProductAsync(string AccountName, int Mark, string ProductInfo, string PrivateKey, object userState)
        {
            if ((this.ByProductOperationCompleted == null))
            {
                this.ByProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByProductOperationCompleted);
            }
            this.InvokeAsync("ByProduct", new object[] {
                    AccountName,
                    Mark,
                    ProductInfo,
                    PrivateKey}, this.ByProductOperationCompleted, userState);
        }

        private void OnByProductOperationCompleted(object arg)
        {
            if ((this.ByProductCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByProductCompleted(this, new ByProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ByProductCompletedEventHandler(object sender, ByProductCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ByProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}