<?xml version="1.0" encoding="utf-8"?><Database Name="SocialShop" Class="AdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.uspCheckLoginBackEnd" Method="uspCheckLoginBackEnd">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Return" Parameter="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminDelete" Method="uspAdminDelete">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminInsert" Method="uspAdminInsert">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="DateCreate" Parameter="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyGetAll" Method="uspCompanyGetAll">
    <ElementType Name="uspCompanyGetAllResult">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParentCompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerCompany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminUpdateInfo" Method="uspAdminUpdateInfo">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspPermissionGetListRoleInUser" Method="uspPermissionGetListRoleInUser">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspPermissionGetListRoleInUserResult">
      <Column Name="PermissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspPermissionGetListRoleNotInUser" Method="uspPermissionGetListRoleNotInUser">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspPermissionGetListRoleNotInUserResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetListToAddShop" Method="uspAdminGetListToAddShop">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetListToAddShopResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminUpdateInfoPersonal" Method="uspAdminUpdateInfoPersonal">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminUpdatePassword" Method="uspAdminUpdatePassword">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyGetChild" Method="uspCompanyGetChild">
    <Parameter Name="ParrentCompanyID" Parameter="parrentCompanyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspCompanyGetChildResult">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParentCompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerCompany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCompanyGetInfo" Method="uspCompanyGetInfo">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspCompanyGetInfoResult">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParentCompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerCompany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCompanyUpdate" Method="uspCompanyUpdate">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Tel" Parameter="tel" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="TagCode" Parameter="tagCode" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ParrentCompany" Parameter="parrentCompany" Type="System.Int32" DbType="Int" />
    <Parameter Name="isCheck" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCustomerDelete" Method="uspCustomerDelete">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyDelete" Method="uspCompanyDelete">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyInsert" Method="uspCompanyInsert">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Tel" Parameter="tel" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="TaxCode" Parameter="taxCode" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ParentCompanyID" Parameter="parentCompanyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="isCheck" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyGetList" Method="uspCompanyGetList">
    <ElementType Name="uspCompanyGetListResult">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParentCompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerCompany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCompanyExistEmailUpdate" Method="uspCompanyExistEmailUpdate">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyExistEmail" Method="uspCompanyExistEmail">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyExistChild" Method="uspCompanyExistChild">
    <Parameter Name="ParrentID" Parameter="parrentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Return" Parameter="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyExistParrent" Method="uspCompanyExistParrent">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Return" Parameter="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyNameExist" Method="uspCompanyNameExist">
    <Parameter Name="companyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyNameUpdateExist" Method="uspCompanyNameUpdateExist">
    <Parameter Name="companyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspCompanyAdminDelete" Method="uspCompanyAdminDelete">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetAll" Method="uspAdminGetAll">
    <ElementType Name="uspAdminGetAllResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCompanyAdminInsert" Method="uspCompanyAdminInsert">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetInfoByUserName" Method="uspAdminGetInfoByUserName">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspAdminGetInfoByUserNameResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetList" Method="uspAdminGetList">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="uspAdminGetListResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetInfoByAdminID" Method="uspAdminGetInfoByAdminID">
    <Parameter Name="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetInfoByAdminIDResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetListCompany" Method="uspAdminGetListCompany">
    <Parameter Name="companyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetListCompanyResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCompanyGetManager" Method="uspCompanyGetManager">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspCompanyGetManagerResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspLogInsert" Method="uspLogInsert">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Function" Parameter="function" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspShopManagerGetListShopByCompany" Method="uspShopManagerGetListShopByCompany">
    <Parameter Name="companyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspShopManagerGetListShopByCompanyResult">
      <Column Name="ShopManagerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspShopManagerInsert" Method="uspShopManagerInsert">
    <Parameter Name="companyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="shopID" Type="System.Int32" DbType="Int" />
    <Parameter Name="contractDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspShopManagerUpdateStatus" Method="uspShopManagerUpdateStatus">
    <Parameter Name="shopManagerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminCheckUserName" Method="uspAdminCheckUserName">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>