<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="SlideShowDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=183.182.100.136;Initial Catalog=Database1;Persist Security Info=True;User ID=tmt" SettingsObjectName="DataContext.Properties.Settings" SettingsPropertyName="Database1ConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspSlideShowDeleteByID" Method="uspSlideShowDeleteByID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspSlideShowGetAll" Method="uspSlideShowGetAll">
    <ElementType Name="uspSlideShowGetAllResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ImgThumb" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspSlideShowGetInfoByID" Method="uspSlideShowGetInfoByID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspSlideShowGetInfoByIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ImgThumb" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspSlideShowInsert" Method="uspSlideShowInsert">
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Img" Parameter="img" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="ImgThumb" Parameter="imgThumb" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspSlideShowUpdateByID" Method="uspSlideShowUpdateByID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Img" Parameter="img" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="ImgThumb" Parameter="imgThumb" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspSlideShowGetAllForPage" Method="uspSlideShowGetAllForPage">
    <Parameter Name="currPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pagesize" Parameter="pagesize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="uspSlideShowGetAllForPageResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ImgThumb" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspSlideShowGetGroup" Method="uspSlideShowGetGroup">
    <ElementType Name="uspSlideShowGetGroupResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ImgThumb" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>