<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="AdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=183.182.100.136;Initial Catalog=Database1;Persist Security Info=True;User ID=tmt" SettingsObjectName="DataContext.Properties.Settings" SettingsPropertyName="Database1ConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspFunctionByParentID" Method="uspFunctionByParentID">
    <Parameter Name="ParentID" Parameter="parentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspFunctionByParentIDResult">
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspFunctionGetInfoByFunctionID" Method="uspFunctionGetInfoByFunctionID">
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspFunctionGetInfoByFunctionIDResult">
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspRoleGetAll" Method="uspRoleGetAll">
    <ElementType Name="uspRoleGetAllResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspFunctionDeleteByFunctionID" Method="uspFunctionDeleteByFunctionID">
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspFunctionInsert" Method="uspFunctionInsert">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Order" Parameter="order" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParrentID" Parameter="parrentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspFunctionUpdateByFunctionID" Method="uspFunctionUpdateByFunctionID">
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Order" Parameter="order" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParrentID" Parameter="parrentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspRoleGetInfoByRoleID" Method="uspRoleGetInfoByRoleID">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspRoleGetInfoByRoleIDResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspRoleUpdateByRoleID" Method="uspRoleUpdateByRoleID">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspRoleInsert" Method="uspRoleInsert">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspRoleDeleteByRoleID" Method="uspRoleDeleteByRoleID">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspRoleUpdateStatus" Method="uspRoleUpdateStatus">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspRoleGetListNotInFunction" Method="uspRoleGetListNotInFunction">
    <Parameter Name="functionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspRoleGetListNotInFunctionResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspRoleGetListByFunction" Method="uspRoleGetListByFunction">
    <Parameter Name="functionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspRoleGetListByFunctionResult">
      <Column Name="RoleFunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspFunctionGetChildInRole" Method="uspFunctionGetChildInRole">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspFunctionGetChildInRoleResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderParent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspRoleFunctionUpdate" Method="uspRoleFunctionUpdate">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Permission" Parameter="permission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetList" Method="uspAdminGetList">
    <Parameter Name="Keyword" Parameter="keyword" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="cur" Type="System.Int32" DbType="Int" />
    <Parameter Name="ps" Type="System.Int32" DbType="Int" />
    <Parameter Name="total" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="uspAdminGetListResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminUpdateStatus" Method="uspAdminUpdateStatus">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminDeleteByAdminID" Method="uspAdminDeleteByAdminID">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetInfoByAdminID" Method="uspAdminGetInfoByAdminID">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetInfoByAdminIDResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminInsert" Method="uspAdminInsert">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="DateCreate" Parameter="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminUpdate" Method="uspAdminUpdate">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetListByRole" Method="uspAdminGetListByRole">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetListByRoleResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PermissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetListNotInRole" Method="uspAdminGetListNotInRole">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetListNotInRoleResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspPermissionInsert" Method="uspPermissionInsert">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspPermissionDeleteByPermissionID" Method="uspPermissionDeleteByPermissionID">
    <Parameter Name="PermissionID" Parameter="permissionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspFunctionGetParentID" Method="uspFunctionGetParentID">
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspFunctionGetIDByUrl" Method="uspFunctionGetIDByUrl">
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspPermissionCheck" Method="uspPermissionCheck">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminLogin" Method="uspAdminLogin">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspAdminLoginResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminUpdateProfile" Method="uspAdminUpdateProfile">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminUpdatePassword" Method="uspAdminUpdatePassword">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordOld" Parameter="passwordOld" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PasswordNew" Parameter="passwordNew" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspConfigUpdate" Method="uspConfigUpdate">
    <Parameter Name="Yahoo1" Parameter="yahoo1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextYahoo1" Parameter="textYahoo1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Yahoo2" Parameter="yahoo2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextYahoo2" Parameter="textYahoo2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Yahoo3" Parameter="yahoo3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextYahoo3" Parameter="textYahoo3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Skype1" Parameter="skype1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextSkype1" Parameter="textSkype1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Skype2" Parameter="skype2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextSkype2" Parameter="textSkype2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Skype3" Parameter="skype3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TextSkype3" Parameter="textSkype3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspConfigGetInfo" Method="uspConfigGetInfo">
    <ElementType Name="uspConfigGetInfoResult">
      <Column Name="Yahoo1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextYahoo1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Yahoo2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextYahoo2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Yahoo3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextYahoo3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Skype1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextSkype1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Skype2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextSkype2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Skype3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TextSkype3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>