//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowBLL.ServiceUpload {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Image", Namespace="http://schemas.datacontract.org/2004/07/Go.Image.Entity")]
    [System.SerializableAttribute()]
    public partial class Image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long _albumIdField;
        
        private int _colorDeepField;
        
        private byte _commentTypeField;
        
        private long _commentsField;
        
        private System.DateTime _createdDateField;
        
        private string _descriptionField;
        
        private string _filePathField;
        
        private long _fileSizeField;
        
        private string _fileTypeField;
        
        private int _heightField;
        
        private long _hitsField;
        
        private long _imageIdField;
        
        private System.DateTime _modifiedDateField;
        
        private int _ordinalInAlbumField;
        
        private string _originalNameField;
        
        private string _publicUrlField;
        
        private byte _rateTypeField;
        
        private long _ratesField;
        
        private string _serverNameField;
        
        private int _statusField;
        
        private byte _tagTypeField;
        
        private string _tagsField;
        
        private int _widthField;
        
        private System.Collections.Generic.Dictionary<string, object> ExtendedPropertiesk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _albumId {
            get {
                return this._albumIdField;
            }
            set {
                if ((this._albumIdField.Equals(value) != true)) {
                    this._albumIdField = value;
                    this.RaisePropertyChanged("_albumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _colorDeep {
            get {
                return this._colorDeepField;
            }
            set {
                if ((this._colorDeepField.Equals(value) != true)) {
                    this._colorDeepField = value;
                    this.RaisePropertyChanged("_colorDeep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte _commentType {
            get {
                return this._commentTypeField;
            }
            set {
                if ((this._commentTypeField.Equals(value) != true)) {
                    this._commentTypeField = value;
                    this.RaisePropertyChanged("_commentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _comments {
            get {
                return this._commentsField;
            }
            set {
                if ((this._commentsField.Equals(value) != true)) {
                    this._commentsField = value;
                    this.RaisePropertyChanged("_comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createdDate {
            get {
                return this._createdDateField;
            }
            set {
                if ((this._createdDateField.Equals(value) != true)) {
                    this._createdDateField = value;
                    this.RaisePropertyChanged("_createdDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._descriptionField, value) != true)) {
                    this._descriptionField = value;
                    this.RaisePropertyChanged("_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _filePath {
            get {
                return this._filePathField;
            }
            set {
                if ((object.ReferenceEquals(this._filePathField, value) != true)) {
                    this._filePathField = value;
                    this.RaisePropertyChanged("_filePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _fileSize {
            get {
                return this._fileSizeField;
            }
            set {
                if ((this._fileSizeField.Equals(value) != true)) {
                    this._fileSizeField = value;
                    this.RaisePropertyChanged("_fileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fileType {
            get {
                return this._fileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._fileTypeField, value) != true)) {
                    this._fileTypeField = value;
                    this.RaisePropertyChanged("_fileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _height {
            get {
                return this._heightField;
            }
            set {
                if ((this._heightField.Equals(value) != true)) {
                    this._heightField = value;
                    this.RaisePropertyChanged("_height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _hits {
            get {
                return this._hitsField;
            }
            set {
                if ((this._hitsField.Equals(value) != true)) {
                    this._hitsField = value;
                    this.RaisePropertyChanged("_hits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _imageId {
            get {
                return this._imageIdField;
            }
            set {
                if ((this._imageIdField.Equals(value) != true)) {
                    this._imageIdField = value;
                    this.RaisePropertyChanged("_imageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _modifiedDate {
            get {
                return this._modifiedDateField;
            }
            set {
                if ((this._modifiedDateField.Equals(value) != true)) {
                    this._modifiedDateField = value;
                    this.RaisePropertyChanged("_modifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ordinalInAlbum {
            get {
                return this._ordinalInAlbumField;
            }
            set {
                if ((this._ordinalInAlbumField.Equals(value) != true)) {
                    this._ordinalInAlbumField = value;
                    this.RaisePropertyChanged("_ordinalInAlbum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _originalName {
            get {
                return this._originalNameField;
            }
            set {
                if ((object.ReferenceEquals(this._originalNameField, value) != true)) {
                    this._originalNameField = value;
                    this.RaisePropertyChanged("_originalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _publicUrl {
            get {
                return this._publicUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._publicUrlField, value) != true)) {
                    this._publicUrlField = value;
                    this.RaisePropertyChanged("_publicUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte _rateType {
            get {
                return this._rateTypeField;
            }
            set {
                if ((this._rateTypeField.Equals(value) != true)) {
                    this._rateTypeField = value;
                    this.RaisePropertyChanged("_rateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _rates {
            get {
                return this._ratesField;
            }
            set {
                if ((this._ratesField.Equals(value) != true)) {
                    this._ratesField = value;
                    this.RaisePropertyChanged("_rates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _serverName {
            get {
                return this._serverNameField;
            }
            set {
                if ((object.ReferenceEquals(this._serverNameField, value) != true)) {
                    this._serverNameField = value;
                    this.RaisePropertyChanged("_serverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _status {
            get {
                return this._statusField;
            }
            set {
                if ((this._statusField.Equals(value) != true)) {
                    this._statusField = value;
                    this.RaisePropertyChanged("_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte _tagType {
            get {
                return this._tagTypeField;
            }
            set {
                if ((this._tagTypeField.Equals(value) != true)) {
                    this._tagTypeField = value;
                    this.RaisePropertyChanged("_tagType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tags {
            get {
                return this._tagsField;
            }
            set {
                if ((object.ReferenceEquals(this._tagsField, value) != true)) {
                    this._tagsField = value;
                    this.RaisePropertyChanged("_tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _width {
            get {
                return this._widthField;
            }
            set {
                if ((this._widthField.Equals(value) != true)) {
                    this._widthField = value;
                    this.RaisePropertyChanged("_width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ExtendedProperties>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, object> ExtendedPropertiesk__BackingField {
            get {
                return this.ExtendedPropertiesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesk__BackingFieldField, value) != true)) {
                    this.ExtendedPropertiesk__BackingFieldField = value;
                    this.RaisePropertyChanged("ExtendedPropertiesk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUpload.IUploadService")]
    public interface IUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_UploadImageBase64", ReplyAction="http://tempuri.org/IUploadService/GoClubs_UploadImageBase64Response")]
        string GoClubs_UploadImageBase64(string content, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetAllAlbumsByUser", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetAllAlbumsByUserResponse")]
        string GoClubs_GetAllAlbumsByUser(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetAllImagesByAlbum", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetAllImagesByAlbumResponse")]
        string GoClubs_GetAllImagesByAlbum(long albumId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetPageImagesByAlbum", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetPageImagesByAlbumResponse")]
        string GoClubs_GetPageImagesByAlbum(long albumId, string returnSize, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetAllImagesInDefaultAlbum", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetAllImagesInDefaultAlbumResponse")]
        string GoClubs_GetAllImagesInDefaultAlbum(long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetPageImagesInDefaultAlbum", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetPageImagesInDefaultAlbumResponse")]
        string GoClubs_GetPageImagesInDefaultAlbum(long accountId, string returnSize, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetAlbumInfo", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetAlbumInfoResponse")]
        string GoClubs_GetAlbumInfo(long albumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_GetImageInfo", ReplyAction="http://tempuri.org/IUploadService/GoClubs_GetImageInfoResponse")]
        string GoClubs_GetImageInfo(long imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoPortal_GetImageByCategoryWithFilter", ReplyAction="http://tempuri.org/IUploadService/GoPortal_GetImageByCategoryWithFilterResponse")]
        string GoPortal_GetImageByCategoryWithFilter(int categoryId, int numberRecord, int feature, int duration, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Embedded_GetAllCategory", ReplyAction="http://tempuri.org/IUploadService/Embedded_GetAllCategoryResponse")]
        System.Xml.Linq.XElement Embedded_GetAllCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Embedded_GetPageAlbumByCategory", ReplyAction="http://tempuri.org/IUploadService/Embedded_GetPageAlbumByCategoryResponse")]
        System.Xml.Linq.XElement Embedded_GetPageAlbumByCategory(int categoryId, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Embedded_GetPageImageByAlbum", ReplyAction="http://tempuri.org/IUploadService/Embedded_GetPageImageByAlbumResponse")]
        System.Xml.Linq.XElement Embedded_GetPageImageByAlbum(long albumId, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Embedded_GetMostViewedAlbum", ReplyAction="http://tempuri.org/IUploadService/Embedded_GetMostViewedAlbumResponse")]
        System.Xml.Linq.XElement Embedded_GetMostViewedAlbum(int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Embedded_GetMostViewedImage", ReplyAction="http://tempuri.org/IUploadService/Embedded_GetMostViewedImageResponse")]
        System.Xml.Linq.XElement Embedded_GetMostViewedImage(int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/ServerInfo", ReplyAction="http://tempuri.org/IUploadService/ServerInfoResponse")]
        string ServerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoNews_UploadImage", ReplyAction="http://tempuri.org/IUploadService/GoNews_UploadImageResponse")]
        string GoNews_UploadImage(byte[] buffer, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoNews_UploadImageBase64", ReplyAction="http://tempuri.org/IUploadService/GoNews_UploadImageBase64Response")]
        string GoNews_UploadImageBase64(string content, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoNews_DeleteImage", ReplyAction="http://tempuri.org/IUploadService/GoNews_DeleteImageResponse")]
        bool GoNews_DeleteImage(long accountId, long imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoNews_GetImageList", ReplyAction="http://tempuri.org/IUploadService/GoNews_GetImageListResponse")]
        string GoNews_GetImageList(long accountId, int pageIndex, int pageSize, ref long totalRecord, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoNews_GetImageListByDate", ReplyAction="http://tempuri.org/IUploadService/GoNews_GetImageListByDateResponse")]
        string GoNews_GetImageListByDate(long accountId, System.DateTime fromDate, System.DateTime toDate, int pageIndex, int pageSize, ref long totalRecord, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Missteen_UploadImageBase64", ReplyAction="http://tempuri.org/IUploadService/Missteen_UploadImageBase64Response")]
        string Missteen_UploadImageBase64(string content, string extention, long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Missteen_UploadImage", ReplyAction="http://tempuri.org/IUploadService/Missteen_UploadImageResponse")]
        string Missteen_UploadImage(byte[] buffer, string extention, long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Missteen_GetNumberOfImageByAccountId", ReplyAction="http://tempuri.org/IUploadService/Missteen_GetNumberOfImageByAccountIdResponse")]
        int Missteen_GetNumberOfImageByAccountId(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/Missteen_UpdateUserInfo", ReplyAction="http://tempuri.org/IUploadService/Missteen_UpdateUserInfoResponse")]
        void Missteen_UpdateUserInfo(long accountId, string registrationNumber, string registrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_UploadImage", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_UploadImageResponse")]
        string GoBlogs_UploadImage(byte[] buffer, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_UploadImageBase64", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_UploadImageBase64Response")]
        string GoBlogs_UploadImageBase64(string content, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetAllImages", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetAllImagesResponse")]
        string GoBlogs_GetAllImages(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetImagesInBlogs", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetImagesInBlogsResponse")]
        string GoBlogs_GetImagesInBlogs(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetImagesInBlogsByDate", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetImagesInBlogsByDateResponse")]
        string GoBlogs_GetImagesInBlogsByDate(long accountId, System.DateTime fromDate, System.DateTime toDate, int pageIndex, int pageSize, ref long totalRecord, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetAllAlbumsByUser", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetAllAlbumsByUserResponse")]
        string GoBlogs_GetAllAlbumsByUser(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetPageAlbumsByUser", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetPageAlbumsByUserResponse")]
        string GoBlogs_GetPageAlbumsByUser(long accountId, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetAllImagesByAlbum", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetAllImagesByAlbumResponse")]
        string GoBlogs_GetAllImagesByAlbum(long albumId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetPageImagesByAlbum", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetPageImagesByAlbumResponse")]
        string GoBlogs_GetPageImagesByAlbum(long albumId, string returnSize, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetAllImagesInDefaultAlbum", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetAllImagesInDefaultAlbumResponse")]
        string GoBlogs_GetAllImagesInDefaultAlbum(long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoBlogs_GetPageImagesInDefaultAlbum", ReplyAction="http://tempuri.org/IUploadService/GoBlogs_GetPageImagesInDefaultAlbumResponse")]
        string GoBlogs_GetPageImagesInDefaultAlbum(long accountId, string returnSize, int pageIndex, int pageSize, ref long totalRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoGTS_GetHotAlbumsByCategory", ReplyAction="http://tempuri.org/IUploadService/GoGTS_GetHotAlbumsByCategoryResponse")]
        string GoGTS_GetHotAlbumsByCategory(int categoryId, int numberRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoGTS_GetMostViewedAlbumsByCategory", ReplyAction="http://tempuri.org/IUploadService/GoGTS_GetMostViewedAlbumsByCategoryResponse")]
        string GoGTS_GetMostViewedAlbumsByCategory(int categoryId, int numberRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoGTS_GetNewestAlbumsByCategory", ReplyAction="http://tempuri.org/IUploadService/GoGTS_GetNewestAlbumsByCategoryResponse")]
        string GoGTS_GetNewestAlbumsByCategory(int categoryId, int numberRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoGTS_GetAllImageByAlbum", ReplyAction="http://tempuri.org/IUploadService/GoGTS_GetAllImageByAlbumResponse")]
        string GoGTS_GetAllImageByAlbum(long albumId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_UploadImage", ReplyAction="http://tempuri.org/IUploadService/GoLocation_UploadImageResponse")]
        string GoLocation_UploadImage(byte[] buffer, string extention, long accountId, string returnSize, ref long imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_UploadImageObject", ReplyAction="http://tempuri.org/IUploadService/GoLocation_UploadImageObjectResponse")]
        WorkFlowBLL.ServiceUpload.Image GoLocation_UploadImageObject(byte[] buffer, string extention, long accountId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_GetImageUrlById", ReplyAction="http://tempuri.org/IUploadService/GoLocation_GetImageUrlByIdResponse")]
        string GoLocation_GetImageUrlById(long imageId, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_GetImageById", ReplyAction="http://tempuri.org/IUploadService/GoLocation_GetImageByIdResponse")]
        WorkFlowBLL.ServiceUpload.Image GoLocation_GetImageById(long imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_DeleteImage", ReplyAction="http://tempuri.org/IUploadService/GoLocation_DeleteImageResponse")]
        bool GoLocation_DeleteImage(long accountId, long imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_DeleteImages", ReplyAction="http://tempuri.org/IUploadService/GoLocation_DeleteImagesResponse")]
        bool GoLocation_DeleteImages(long accountId, long[] imageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoLocation_GetImageList", ReplyAction="http://tempuri.org/IUploadService/GoLocation_GetImageListResponse")]
        string GoLocation_GetImageList(long accountId, int pageIndex, int pageSize, ref long totalRecord, string returnSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GoClubs_UploadImage", ReplyAction="http://tempuri.org/IUploadService/GoClubs_UploadImageResponse")]
        string GoClubs_UploadImage(byte[] buffer, string extention, long accountId, string returnSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadServiceChannel : WorkFlowBLL.ServiceUpload.IUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceClient : System.ServiceModel.ClientBase<WorkFlowBLL.ServiceUpload.IUploadService>, WorkFlowBLL.ServiceUpload.IUploadService {
        
        public UploadServiceClient() {
        }
        
        public UploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GoClubs_UploadImageBase64(string content, string extention, long accountId, string returnSize) {
            return base.Channel.GoClubs_UploadImageBase64(content, extention, accountId, returnSize);
        }
        
        public string GoClubs_GetAllAlbumsByUser(long accountId) {
            return base.Channel.GoClubs_GetAllAlbumsByUser(accountId);
        }
        
        public string GoClubs_GetAllImagesByAlbum(long albumId, string returnSize) {
            return base.Channel.GoClubs_GetAllImagesByAlbum(albumId, returnSize);
        }
        
        public string GoClubs_GetPageImagesByAlbum(long albumId, string returnSize, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.GoClubs_GetPageImagesByAlbum(albumId, returnSize, pageIndex, pageSize, ref totalRecord);
        }
        
        public string GoClubs_GetAllImagesInDefaultAlbum(long accountId, string returnSize) {
            return base.Channel.GoClubs_GetAllImagesInDefaultAlbum(accountId, returnSize);
        }
        
        public string GoClubs_GetPageImagesInDefaultAlbum(long accountId, string returnSize, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.GoClubs_GetPageImagesInDefaultAlbum(accountId, returnSize, pageIndex, pageSize, ref totalRecord);
        }
        
        public string GoClubs_GetAlbumInfo(long albumId) {
            return base.Channel.GoClubs_GetAlbumInfo(albumId);
        }
        
        public string GoClubs_GetImageInfo(long imageId) {
            return base.Channel.GoClubs_GetImageInfo(imageId);
        }
        
        public string GoPortal_GetImageByCategoryWithFilter(int categoryId, int numberRecord, int feature, int duration, string returnSize) {
            return base.Channel.GoPortal_GetImageByCategoryWithFilter(categoryId, numberRecord, feature, duration, returnSize);
        }
        
        public System.Xml.Linq.XElement Embedded_GetAllCategory() {
            return base.Channel.Embedded_GetAllCategory();
        }
        
        public System.Xml.Linq.XElement Embedded_GetPageAlbumByCategory(int categoryId, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.Embedded_GetPageAlbumByCategory(categoryId, pageIndex, pageSize, ref totalRecord);
        }
        
        public System.Xml.Linq.XElement Embedded_GetPageImageByAlbum(long albumId, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.Embedded_GetPageImageByAlbum(albumId, pageIndex, pageSize, ref totalRecord);
        }
        
        public System.Xml.Linq.XElement Embedded_GetMostViewedAlbum(int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.Embedded_GetMostViewedAlbum(pageIndex, pageSize, ref totalRecord);
        }
        
        public System.Xml.Linq.XElement Embedded_GetMostViewedImage(int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.Embedded_GetMostViewedImage(pageIndex, pageSize, ref totalRecord);
        }
        
        public string ServerInfo() {
            return base.Channel.ServerInfo();
        }
        
        public string GoNews_UploadImage(byte[] buffer, string extention, long accountId, string returnSize) {
            return base.Channel.GoNews_UploadImage(buffer, extention, accountId, returnSize);
        }
        
        public string GoNews_UploadImageBase64(string content, string extention, long accountId, string returnSize) {
            return base.Channel.GoNews_UploadImageBase64(content, extention, accountId, returnSize);
        }
        
        public bool GoNews_DeleteImage(long accountId, long imageId) {
            return base.Channel.GoNews_DeleteImage(accountId, imageId);
        }
        
        public string GoNews_GetImageList(long accountId, int pageIndex, int pageSize, ref long totalRecord, string returnSize) {
            return base.Channel.GoNews_GetImageList(accountId, pageIndex, pageSize, ref totalRecord, returnSize);
        }
        
        public string GoNews_GetImageListByDate(long accountId, System.DateTime fromDate, System.DateTime toDate, int pageIndex, int pageSize, ref long totalRecord, string returnSize) {
            return base.Channel.GoNews_GetImageListByDate(accountId, fromDate, toDate, pageIndex, pageSize, ref totalRecord, returnSize);
        }
        
        public string Missteen_UploadImageBase64(string content, string extention, long accountId) {
            return base.Channel.Missteen_UploadImageBase64(content, extention, accountId);
        }
        
        public string Missteen_UploadImage(byte[] buffer, string extention, long accountId) {
            return base.Channel.Missteen_UploadImage(buffer, extention, accountId);
        }
        
        public int Missteen_GetNumberOfImageByAccountId(long accountId) {
            return base.Channel.Missteen_GetNumberOfImageByAccountId(accountId);
        }
        
        public void Missteen_UpdateUserInfo(long accountId, string registrationNumber, string registrationName) {
            base.Channel.Missteen_UpdateUserInfo(accountId, registrationNumber, registrationName);
        }
        
        public string GoBlogs_UploadImage(byte[] buffer, string extention, long accountId, string returnSize) {
            return base.Channel.GoBlogs_UploadImage(buffer, extention, accountId, returnSize);
        }
        
        public string GoBlogs_UploadImageBase64(string content, string extention, long accountId, string returnSize) {
            return base.Channel.GoBlogs_UploadImageBase64(content, extention, accountId, returnSize);
        }
        
        public string GoBlogs_GetAllImages(long accountId) {
            return base.Channel.GoBlogs_GetAllImages(accountId);
        }
        
        public string GoBlogs_GetImagesInBlogs(long accountId) {
            return base.Channel.GoBlogs_GetImagesInBlogs(accountId);
        }
        
        public string GoBlogs_GetImagesInBlogsByDate(long accountId, System.DateTime fromDate, System.DateTime toDate, int pageIndex, int pageSize, ref long totalRecord, string returnSize) {
            return base.Channel.GoBlogs_GetImagesInBlogsByDate(accountId, fromDate, toDate, pageIndex, pageSize, ref totalRecord, returnSize);
        }
        
        public string GoBlogs_GetAllAlbumsByUser(long accountId) {
            return base.Channel.GoBlogs_GetAllAlbumsByUser(accountId);
        }
        
        public string GoBlogs_GetPageAlbumsByUser(long accountId, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.GoBlogs_GetPageAlbumsByUser(accountId, pageIndex, pageSize, ref totalRecord);
        }
        
        public string GoBlogs_GetAllImagesByAlbum(long albumId, string returnSize) {
            return base.Channel.GoBlogs_GetAllImagesByAlbum(albumId, returnSize);
        }
        
        public string GoBlogs_GetPageImagesByAlbum(long albumId, string returnSize, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.GoBlogs_GetPageImagesByAlbum(albumId, returnSize, pageIndex, pageSize, ref totalRecord);
        }
        
        public string GoBlogs_GetAllImagesInDefaultAlbum(long accountId, string returnSize) {
            return base.Channel.GoBlogs_GetAllImagesInDefaultAlbum(accountId, returnSize);
        }
        
        public string GoBlogs_GetPageImagesInDefaultAlbum(long accountId, string returnSize, int pageIndex, int pageSize, ref long totalRecord) {
            return base.Channel.GoBlogs_GetPageImagesInDefaultAlbum(accountId, returnSize, pageIndex, pageSize, ref totalRecord);
        }
        
        public string GoGTS_GetHotAlbumsByCategory(int categoryId, int numberRecord) {
            return base.Channel.GoGTS_GetHotAlbumsByCategory(categoryId, numberRecord);
        }
        
        public string GoGTS_GetMostViewedAlbumsByCategory(int categoryId, int numberRecord) {
            return base.Channel.GoGTS_GetMostViewedAlbumsByCategory(categoryId, numberRecord);
        }
        
        public string GoGTS_GetNewestAlbumsByCategory(int categoryId, int numberRecord) {
            return base.Channel.GoGTS_GetNewestAlbumsByCategory(categoryId, numberRecord);
        }
        
        public string GoGTS_GetAllImageByAlbum(long albumId, string returnSize) {
            return base.Channel.GoGTS_GetAllImageByAlbum(albumId, returnSize);
        }
        
        public string GoLocation_UploadImage(byte[] buffer, string extention, long accountId, string returnSize, ref long imageId) {
            return base.Channel.GoLocation_UploadImage(buffer, extention, accountId, returnSize, ref imageId);
        }
        
        public WorkFlowBLL.ServiceUpload.Image GoLocation_UploadImageObject(byte[] buffer, string extention, long accountId, string returnSize) {
            return base.Channel.GoLocation_UploadImageObject(buffer, extention, accountId, returnSize);
        }
        
        public string GoLocation_GetImageUrlById(long imageId, string returnSize) {
            return base.Channel.GoLocation_GetImageUrlById(imageId, returnSize);
        }
        
        public WorkFlowBLL.ServiceUpload.Image GoLocation_GetImageById(long imageId) {
            return base.Channel.GoLocation_GetImageById(imageId);
        }
        
        public bool GoLocation_DeleteImage(long accountId, long imageId) {
            return base.Channel.GoLocation_DeleteImage(accountId, imageId);
        }
        
        public bool GoLocation_DeleteImages(long accountId, long[] imageId) {
            return base.Channel.GoLocation_DeleteImages(accountId, imageId);
        }
        
        public string GoLocation_GetImageList(long accountId, int pageIndex, int pageSize, ref long totalRecord, string returnSize) {
            return base.Channel.GoLocation_GetImageList(accountId, pageIndex, pageSize, ref totalRecord, returnSize);
        }
        
        public string GoClubs_UploadImage(byte[] buffer, string extention, long accountId, string returnSize) {
            return base.Channel.GoClubs_UploadImage(buffer, extention, accountId, returnSize);
        }
    }
}
